# Generated by Django 5.0.3 on 2024-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('ingredient_type', models.ManyToManyField(to='cookbook.ingredient_type')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('steps', models.TextField(max_length=400)),
                ('recipe_ingredients', models.ManyToManyField(blank=True, to='cookbook.ingredient')),
                ('recipe_type', models.ManyToManyField(to='cookbook.recipe_type')),
            ],
        ),
    ]
