# Generated by Django 5.0.4 on 2024-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ammounts',
            field=models.CharField(default='1 egg', max_length=200),
            preserve_default=False,
        ),
    ]
