# Generated by Django 5.1.3 on 2024-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_recipe_recipe_ammounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.CharField(default=30, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ammount',
        ),
    ]
