# Generated by Django 5.1.4 on 2024-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image_credit',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
